const admin = require("firebase-admin");
const sgMail = require("@sendgrid/mail");
const { schedule } = require("@netlify/functions");

const handler = async function(event, context) {
  console.log("⏰ Running Smart Expiry & Low Stock Check...");

  // 1. SETUP KEYS
  if (!process.env.FIREBASE_SERVICE_ACCOUNT) {
    console.error("❌ ERROR: FIREBASE_SERVICE_ACCOUNT is missing.");
    return { statusCode: 500 };
  }

  const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
  const DB_URL = process.env.FIREBASE_DB_URL;
  const SENDGRID_KEY = process.env.SENDGRID_API_KEY;
  const SENDER_EMAIL = process.env.SENDER_EMAIL;

  if (!admin.apps.length) {
    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      databaseURL: DB_URL
    });
  }

  const db = admin.database();
  sgMail.setApiKey(SENDGRID_KEY);

  // 2. FETCH DATA
  const invRef = db.ref("inventory_live_v1");
  const contactsRef = db.ref("study_contacts");
  
  const [invSnap, contactSnap] = await Promise.all([invRef.once("value"), contactsRef.once("value")]);
  const inventory = invSnap.val() || {};
  const contacts = contactSnap.val() || {};

  const today = new Date();
  const alerts = {}; 
  
  // MILESTONES: Approaching expiry triggers
  const MILESTONES = [30, 15, 5];

  // TRACK STOCK LEVELS (Study -> Visit -> Count)
  const stockCounts = {}; 

  // 3. ANALYZE INVENTORY
  Object.values(inventory).forEach(item => {
    const study = item.study || "Unknown";
    const visit = item.visit || "Unknown";

    // Initialize the stock tracker for this specific Study & Visit
    if (!stockCounts[study]) stockCounts[study] = {};
    if (stockCounts[study][visit] === undefined) stockCounts[study][visit] = 0;

    // Only count items that are actually in stock
    if (item.status === 'Available') {
      stockCounts[study][visit]++;

      // Expiry Logic
      if (item.expiry) {
        const expDate = new Date(item.expiry);
        const diffTime = expDate - today;
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

        if (MILESTONES.includes(diffDays) || diffDays <= 0) {
          if (!alerts[study]) alerts[study] = { expiring: [], lowStock: [] };
          
          let urgency = "⚠️ Warning";
          if (diffDays === 15) urgency = "🟠 Reminder";
          if (diffDays === 5) urgency = "🔴 URGENT";
          if (diffDays <= 0) urgency = "☠️ EXPIRED";

          alerts[study].expiring.push({
            barcode: item.barcode,
            visit: item.visit,
            expiry: item.expiry,
            daysLeft: diffDays,
            label: urgency
          });
        }
      }
    }
  });

  // 4. CHECK FOR LOW STOCK (< 5)
  for (const study in stockCounts) {
    for (const visit in stockCounts[study]) {
      const currentStock = stockCounts[study][visit];
      
      // Trigger if stock drops below 5
      if (currentStock < 5) {
        if (!alerts[study]) alerts[study] = { expiring: [], lowStock: [] };
        alerts[study].lowStock.push({
          visit: visit,
          count: currentStock
        });
      }
    }
  }

  // 5. SEND EMAILS
  const emailPromises = [];

  for (const [studyName, studyAlerts] of Object.entries(alerts)) {
    // Skip if there are no alerts for this study
    if (studyAlerts.expiring.length === 0 && studyAlerts.lowStock.length === 0) continue;

    let recipient = null;
    Object.values(contacts).forEach(c => {
      if(c.name.toLowerCase() === studyName.toLowerCase()) recipient = c.email;
    });

    if (recipient) {
      console.log(`📧 Sending alerts for ${studyName} to ${recipient}`);
      
      let htmlBody = `
        <div style="font-family: sans-serif; color: #333;">
          <h2 style="color: #d32f2f;">Daily Inventory Alerts: ${studyName}</h2>
          <p>Please review the following inventory alerts generated by LIMS.</p>
      `;

      // Inject Low Stock HTML if applicable
      if (studyAlerts.lowStock.length > 0) {
        htmlBody += `<h3 style="color: #e65100;">📉 Low Stock Warning</h3><ul>`;
        studyAlerts.lowStock.forEach(ls => {
            let color = ls.count === 0 ? "red" : "black";
            htmlBody += `<li><strong>${ls.visit}:</strong> <span style="color:${color}; font-weight:bold;">Only ${ls.count} kit(s) remaining!</span></li>`;
        });
        htmlBody += `</ul>`;
      }

      // Inject Expiring HTML if applicable
      if (studyAlerts.expiring.length > 0) {
        htmlBody += `<h3 style="color: #d32f2f;">⏳ Expiration Actions Required</h3><ul>`;
        studyAlerts.expiring.forEach(ex => {
            htmlBody += `<li><strong>${ex.label}:</strong> ${ex.barcode} (${ex.visit}) - Expires ${ex.expiry} (${ex.daysLeft} days)</li>`;
        });
        htmlBody += `</ul>`;
      }

      htmlBody += `
          <hr>
          <p style="font-size: 0.8em; color: #666;">Automated LIMS Notification from Netlify.</p>
        </div>
      `;

      const msg = {
        to: recipient,
        from: {
          email: SENDER_EMAIL,
          name: "LIMS Inventory System"
        },
        subject: `⚠️ ACTION REQUIRED: Inventory Alerts for ${studyName}`,
        html: htmlBody,
      };
      emailPromises.push(sgMail.send(msg));
    }
  }

  await Promise.all(emailPromises);
  console.log("✅ Check Complete.");
  return { statusCode: 200 };
};

module.exports.handler = schedule("0 8 * * *", handler);
